(* Content-type: application/vnd.wolfram.mathematica *)

(*** Wolfram Notebook File ***)
(* http://www.wolfram.com/nb *)

(* CreatedBy='Mathematica 10.0' *)

(*CacheID: 234*)
(* Internal cache information:
NotebookFileLineBreakTest
NotebookFileLineBreakTest
NotebookDataPosition[       158,          7]
NotebookDataLength[     30083,        667]
NotebookOptionsPosition[     28199,        625]
NotebookOutlinePosition[     28598,        642]
CellTagsIndexPosition[     28555,        639]
WindowFrame->Normal*)

(* Beginning of Notebook Content *)
Notebook[{

Cell[CellGroupData[{
Cell["Simple Box Design Widget", "Title",
 CellChangeTimes->{{3.6207604105424023`*^9, 3.6207604167107553`*^9}, {
  3.6208609267970285`*^9, 3.6208609271714287`*^9}, {3.620861273866438*^9, 
  3.620861275473241*^9}, {3.620883421956933*^9, 3.6208834243281374`*^9}, {
  3.6220706110283947`*^9, 
  3.6220706167483945`*^9}},ExpressionUUID->"f934e75a-8f02-49ca-83d8-\
c79ba5b801fd"],

Cell["Example of controlling Rhino from a Manipulate.", "Text",
 CellChangeTimes->{{3.668171147134261*^9, 
  3.6681711566658*^9}},ExpressionUUID->"09d236c1-1394-4427-a88e-743caae89d70"],

Cell["Drag sliders to control the size and position of a box.", "Text",
 CellChangeTimes->{{3.668171163155343*^9, 
  3.668171183996008*^9}},ExpressionUUID->"6c0e0dc9-3c31-439a-b773-\
4b0e70fd3ab6"],

Cell["\<\
Click the \[OpenCurlyDoubleQuote]new box\[CloseCurlyDoubleQuote] button to \
create a new box coincident with the current box. Use the sliders to \
reposition/resize it.\
\>", "Text",
 CellChangeTimes->{{3.668171196740636*^9, 3.6681712480935316`*^9}, {
  3.668341919524973*^9, 
  3.668341979280487*^9}},ExpressionUUID->"c3da9f8b-ac13-45ac-87b8-\
0ecf039bc4d3"],

Cell["\<\
Change the box rendering by selecting from the \[OpenCurlyDoubleQuote]display \
mode\[CloseCurlyDoubleQuote] menus.\
\>", "Text",
 CellChangeTimes->{{3.668171250761012*^9, 3.668171274627941*^9}, {
  3.668342007916317*^9, 
  3.668342010256302*^9}},ExpressionUUID->"824a49db-09a4-4f39-9cf0-\
f65c144c7032"],

Cell[CellGroupData[{

Cell["Agenda", "Section",
 CellChangeTimes->{{3.6220705492173944`*^9, 
  3.622070549864394*^9}},ExpressionUUID->"571f6223-53b4-452f-90af-\
6fb0e6651423"],

Cell["- add a picker to connect the manipulate to a selected box", "Text",
 CellChangeTimes->{{3.6209010110481687`*^9, 3.6209010291130004`*^9}, 
   3.6209225521863475`*^9, {3.6220705600083942`*^9, 
   3.6220705638633947`*^9}},ExpressionUUID->"3bc6e92a-7475-4fe8-a316-\
527ca4179321"]
}, Closed]],

Cell[CellGroupData[{

Cell["Setup", "Section",
 CellChangeTimes->{{3.6220705088503942`*^9, 
  3.622070516482394*^9}},ExpressionUUID->"5a626873-a455-47c0-9d7d-\
563dcb4caf65"],

Cell["In Rhino, execute WolframConnect.", "Text",
 CellChangeTimes->{{3.6220705912773943`*^9, 3.6220706257713947`*^9}, {
  3.7317606968623343`*^9, 
  3.731760700213232*^9}},ExpressionUUID->"05e8fc1f-af24-411a-a303-\
6825d0808988"]
}, Open  ]],

Cell[CellGroupData[{

Cell["Initialization", "Section",
 InitializationGroup->True,
 CellChangeTimes->{{3.6220705355133944`*^9, 3.6220705394013944`*^9}, {
  3.622635662232705*^9, 
  3.6226356640267625`*^9}},ExpressionUUID->"af1b65cd-c32e-4617-95fe-\
7357994531af"],

Cell["A simple box design widget.", "Text",
 CellChangeTimes->{{3.6208834294137464`*^9, 
  3.620883456403396*^9}},ExpressionUUID->"394c5d7b-7b70-4a24-a708-\
c11c106486c8"],

Cell[BoxData[
 RowBox[{
  RowBox[{"BoxDesignWidget", "[", "]"}], ":=", "\[IndentingNewLine]", 
  RowBox[{"DynamicModule", "[", 
   RowBox[{
    RowBox[{"{", 
     RowBox[{"doc", ",", " ", "guid", ",", " ", "displayModes"}], "}"}], ",", 
    "\[IndentingNewLine]", 
    RowBox[{
     RowBox[{
     "LoadNETType", "[", "\"\<Rhino.Display.DisplayModeDescription\>\"", 
      "]"}], ";", "\[IndentingNewLine]", 
     RowBox[{"LoadNETType", "[", "\"\<Rhino.RhinoApp\>\"", "]"}], ";", 
     "\[IndentingNewLine]", 
     RowBox[{"displayModes", " ", "=", " ", 
      RowBox[{
       RowBox[{
        RowBox[{"(", 
         RowBox[{"#", "@", "EnglishName"}], ")"}], "&"}], " ", "/@", " ", 
       RowBox[{
       "Rhino`Display`DisplayModeDescription`GetDisplayModes", "[", "]"}]}]}],
      ";", "\[IndentingNewLine]", 
     RowBox[{"Manipulate", "[", "\[IndentingNewLine]", 
      RowBox[{
       RowBox[{"NETBlock", "[", "\[IndentingNewLine]", 
        RowBox[{
         RowBox[{"doc", "@", 
          RowBox[{"Objects", "@", 
           RowBox[{"Replace", "[", 
            RowBox[{"guid", ",", "\[IndentingNewLine]", 
             RowBox[{"Brep`CreateFromBox", "[", 
              RowBox[{"NETNew", "[", 
               RowBox[{
               "\"\<Rhino.Geometry.BoundingBox\>\"", ",", 
                "\[IndentingNewLine]", 
                RowBox[{"NETNew", "[", 
                 RowBox[{
                 "\"\<Rhino.Geometry.Point3d\>\"", ",", " ", "x", ",", "y", 
                  ",", "z"}], "]"}], ",", "\[IndentingNewLine]", 
                RowBox[{"NETNew", "[", 
                 RowBox[{"\"\<Rhino.Geometry.Point3d\>\"", ",", " ", 
                  RowBox[{"x", "+", "l"}], ",", 
                  RowBox[{"y", "+", "w"}], ",", 
                  RowBox[{"z", "+", "h"}]}], "]"}]}], "]"}], "]"}]}], 
            "]"}]}]}], ";", "\[IndentingNewLine]", 
         RowBox[{"doc", "@", 
          RowBox[{"Views", "@", 
           RowBox[{"Redraw", "[", "]"}]}]}], ";", "\[IndentingNewLine]", 
         "\"\<\>\""}], "\[IndentingNewLine]", 
        RowBox[{"(*", " ", 
         RowBox[{"Row", "[", 
          RowBox[{
           RowBox[{"{", 
            RowBox[{"\"\<pos:\>\"", ",", 
             RowBox[{"{", 
              RowBox[{"x", ",", "y", ",", "z"}], "}"}], ",", " ", 
             "\"\< dim:\>\"", ",", 
             RowBox[{"{", 
              RowBox[{"l", ",", "w", ",", "h"}], "}"}]}], "}"}], ",", 
           "\"\< \>\""}], "]"}], " ", "*)"}], "\[IndentingNewLine]", "]"}], 
       ",", "\[IndentingNewLine]", 
       RowBox[{"ActionMenu", "[", 
        RowBox[{"\"\<display mode\>\"", ",", 
         RowBox[{
          RowBox[{
           RowBox[{"(", 
            RowBox[{"#", "\[RuleDelayed]", "\[IndentingNewLine]", 
             RowBox[{"(*", " ", 
              RowBox[{
              "for", " ", "some", " ", "reason", " ", "it", " ", "takes", " ",
                "two", " ", "invocations", " ", "to", " ", "set", " ", "all", 
               " ", 
               RowBox[{"viewports", "'"}], " ", "display", " ", "modes"}], 
              " ", "*)"}], "\[IndentingNewLine]", 
             RowBox[{"(", 
              RowBox[{
               RowBox[{"RhinoApp`RunScript", "[", 
                RowBox[{
                 RowBox[{
                 "\"\<_SetDisplayMode Viewport=All \\\"\>\"", "<>", "#", 
                  "<>", "\"\<\\\" _Enter\>\""}], ",", "False"}], "]"}], ";", 
               "\[IndentingNewLine]", 
               RowBox[{"RhinoApp`RunScript", "[", 
                RowBox[{
                 RowBox[{
                 "\"\<_SetDisplayMode Viewport=All \\\"\>\"", "<>", "#", 
                  "<>", "\"\<\\\" _Enter\>\""}], ",", "False"}], "]"}]}], 
              ")"}]}], "\[IndentingNewLine]", ")"}], "&"}], " ", "/@", " ", 
          "displayModes"}], ",", 
         RowBox[{"ImageSize", "\[Rule]", "Medium"}]}], "]"}], ",", 
       "\[IndentingNewLine]", "Delimiter", ",", "\[IndentingNewLine]", 
       RowBox[{"Grid", "[", 
        RowBox[{
         RowBox[{"Transpose", "@", 
          RowBox[{"{", "\[IndentingNewLine]", 
           RowBox[{
            RowBox[{"{", 
             RowBox[{
             "\"\<length\>\"", ",", "\"\<width\>\"", ",", "\"\<height\>\""}], 
             "}"}], ",", "\[IndentingNewLine]", 
            RowBox[{"{", 
             RowBox[{
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"l", ",", "1", ",", "\"\<\>\""}], "}"}], ",", "1", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}], 
              ",", "\[IndentingNewLine]", 
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"w", ",", "1", ",", "\"\<\>\""}], "}"}], ",", "1", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}], 
              ",", "\[IndentingNewLine]", 
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"h", ",", "1", ",", "\"\<\>\""}], "}"}], ",", "1", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}]}], 
             "}"}], ",", "\[IndentingNewLine]", 
            RowBox[{"{", 
             RowBox[{"\"\<\>\"", ",", "\"\<\>\"", ",", "\"\<\>\""}], "}"}], 
            ",", "\[IndentingNewLine]", 
            RowBox[{"{", 
             RowBox[{"\"\<x\>\"", ",", "\"\<y\>\"", ",", "\"\<z\>\""}], "}"}],
             ",", "\[IndentingNewLine]", 
            RowBox[{"{", 
             RowBox[{
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"x", ",", "0", ",", "\"\<\>\""}], "}"}], ",", "0", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}], 
              ",", "\[IndentingNewLine]", 
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"y", ",", "0", ",", "\"\<\>\""}], "}"}], ",", "0", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}], 
              ",", "\[IndentingNewLine]", 
              RowBox[{"Control", "[", 
               RowBox[{"{", 
                RowBox[{
                 RowBox[{"{", 
                  RowBox[{"z", ",", "0", ",", "\"\<\>\""}], "}"}], ",", "0", 
                 ",", "10", ",", "1", ",", 
                 RowBox[{"ImageSize", "\[Rule]", "Small"}]}], "}"}], "]"}]}], 
             "}"}]}], "\[IndentingNewLine]", "}"}]}], ",", 
         RowBox[{"Alignment", "\[Rule]", 
          RowBox[{"{", 
           RowBox[{"Right", ",", "Left", ",", "Right", ",", "Left"}], 
           "}"}]}]}], "]"}], ",", "\[IndentingNewLine]", "\"\<\>\"", ",", 
       "\[IndentingNewLine]", 
       RowBox[{"Button", "[", 
        RowBox[{"\"\<new box\>\"", ",", "\[IndentingNewLine]", 
         RowBox[{
          RowBox[{"guid", "=", 
           RowBox[{"doc", "@", 
            RowBox[{"Objects", "@", 
             RowBox[{"Add", "[", 
              RowBox[{"Brep`CreateFromBox", "[", 
               RowBox[{"NETNew", "[", 
                RowBox[{
                "\"\<Rhino.Geometry.BoundingBox\>\"", ",", 
                 "\[IndentingNewLine]", 
                 RowBox[{"NETNew", "[", 
                  RowBox[{
                  "\"\<Rhino.Geometry.Point3d\>\"", ",", " ", "x", ",", "y", 
                   ",", "z"}], "]"}], ",", "\[IndentingNewLine]", 
                 RowBox[{"NETNew", "[", 
                  RowBox[{"\"\<Rhino.Geometry.Point3d\>\"", ",", "  ", 
                   RowBox[{"x", "+", "l"}], ",", 
                   RowBox[{"y", "+", "w"}], ",", 
                   RowBox[{"z", "+", "h"}]}], "]"}]}], "]"}], "]"}], 
              "]"}]}]}]}], ";", "\[IndentingNewLine]", 
          RowBox[{"doc", "@", 
           RowBox[{"Views", "@", 
            RowBox[{"Redraw", "[", "]"}]}]}]}]}], "\[IndentingNewLine]", 
        "]"}], ",", "\[IndentingNewLine]", "\"\<\>\"", ",", 
       "\[IndentingNewLine]", 
       RowBox[{"Initialization", "\[RuleDelayed]", 
        RowBox[{"Block", "[", 
         RowBox[{
          RowBox[{"{", "}"}], ",", "\[IndentingNewLine]", 
          RowBox[{
           RowBox[{"LoadNETType", "[", "\"\<Rhino.RhinoDoc\>\"", "]"}], ";", 
           "\[IndentingNewLine]", 
           RowBox[{"LoadNETType", "[", "\"\<Rhino.Geometry.Brep\>\"", "]"}], 
           ";", "\[IndentingNewLine]", 
           RowBox[{
           "LoadNETType", "[", "\"\<Rhino.Display.DisplayModeDescription\>\"",
             "]"}], ";", "\[IndentingNewLine]", 
           RowBox[{"LoadNETType", "[", "\"\<Rhino.RhinoApp\>\"", "]"}], ";", 
           "\[IndentingNewLine]", 
           RowBox[{"doc", "=", "RhinoDoc`ActiveDoc"}], ";", 
           "\[IndentingNewLine]", 
           RowBox[{"guid", "=", 
            RowBox[{"doc", "@", 
             RowBox[{"Objects", "@", 
              RowBox[{"Add", "[", 
               RowBox[{"Brep`CreateFromBox", "[", 
                RowBox[{"NETNew", "[", 
                 RowBox[{
                 "\"\<Rhino.Geometry.BoundingBox\>\"", ",", 
                  "\[IndentingNewLine]", 
                  RowBox[{"NETNew", "[", 
                   RowBox[{
                   "\"\<Rhino.Geometry.Point3d\>\"", ",", " ", "0", ",", "0", 
                    ",", "0"}], "]"}], ",", "\[IndentingNewLine]", 
                  RowBox[{"NETNew", "[", 
                   RowBox[{
                   "\"\<Rhino.Geometry.Point3d\>\"", ",", " ", "1", ",", "1", 
                    ",", "1"}], "]"}]}], "]"}], "]"}], "]"}]}]}]}], ";", 
           "\[IndentingNewLine]", 
           RowBox[{"doc", "@", 
            RowBox[{"Views", "@", 
             RowBox[{"Redraw", "[", "]"}]}]}]}]}], "\[IndentingNewLine]", 
         "]"}]}]}], "\[IndentingNewLine]", "]"}]}]}], "\[IndentingNewLine]", 
   "]"}]}]], "Input",
 CellChangeTimes->{{3.620861236005172*^9, 3.620861265894824*^9}, {
   3.620862175112627*^9, 3.6208623442637243`*^9}, {3.620862376602581*^9, 
   3.620862426600669*^9}, {3.6208625274704456`*^9, 3.620862540730469*^9}, {
   3.6208627629840593`*^9, 3.6208627845900974`*^9}, {3.620882392183524*^9, 
   3.6208823967387323`*^9}, {3.6208825294949656`*^9, 
   3.6208825433165903`*^9}, {3.6208826059663*^9, 3.6208826113951097`*^9}, {
   3.6208828681715603`*^9, 3.6208828989504147`*^9}, {3.6208829517565074`*^9, 
   3.6208829882761717`*^9}, {3.620883019195426*^9, 3.6208830361526556`*^9}, {
   3.6208831199872026`*^9, 3.620883140236038*^9}, {3.6208831937285323`*^9, 
   3.6208831958189363`*^9}, {3.6208832399514136`*^9, 3.620883302257923*^9}, {
   3.6208834816754403`*^9, 3.6208836564269476`*^9}, {3.620884767989106*^9, 
   3.6208847830275326`*^9}, 3.6209002366337276`*^9, {3.620900310874258*^9, 
   3.6209003443675165`*^9}, {3.62090042962354*^9, 3.6209006414211197`*^9}, {
   3.620900704055229*^9, 3.6209007103108406`*^9}, {3.6209008012122*^9, 
   3.6209008192458315`*^9}, {3.6209008628323083`*^9, 3.620900890397557*^9}, {
   3.6209009471660566`*^9, 3.620900947556057*^9}, {3.6226356496279435`*^9, 
   3.6226356558677006`*^9}, {3.62263601581553*^9, 3.622636291754629*^9}, {
   3.622636360114093*^9, 3.6226363675397882`*^9}, {3.62263639923607*^9, 
   3.6226365275403776`*^9}, {3.622636607035101*^9, 3.622636627158327*^9}, 
   3.6681710095393105`*^9},ExpressionUUID->"b68cf3d2-6ef4-4f9c-972d-\
12d8977d1b61"]
}, Closed]],

Cell[CellGroupData[{

Cell["Box Design Widget", "Section",
 CellChangeTimes->{{3.622635690532012*^9, 
  3.62263569422933*^9}},ExpressionUUID->"b0ccd80e-5534-4d72-9a41-\
1412106bc697"],

Cell[CellGroupData[{

Cell[BoxData[
 RowBox[{"BoxDesignWidget", "[", "]"}]], "Input",
 CellChangeTimes->{{3.622635696148192*^9, 
  3.6226356995179*^9}},ExpressionUUID->"02b37985-8aff-4e0b-aa38-4919feb0b032"],

Cell[BoxData[
 DynamicModuleBox[{$CellContext`doc$$ = 
  NETLink`Objects`NETObject$807534751383553, $CellContext`guid$$ = 
  NETLink`Objects`NETObject$25078155966414849, $CellContext`displayModes$$ = {
  "Wireframe", "Shaded", "Rendered", "Ghosted", "X-Ray", "Technical", 
   "Artistic", "Pen", "Raytraced with Neon"}}, 
  TagBox[
   StyleBox[
    DynamicModuleBox[{$CellContext`h$$ = 1, $CellContext`l$$ = 
     2, $CellContext`w$$ = 4, $CellContext`x$$ = 1, $CellContext`y$$ = 
     1, $CellContext`z$$ = 7, Typeset`show$$ = True, 
     Typeset`bookmarkList$$ = {}, Typeset`bookmarkMode$$ = "Menu", 
     Typeset`animator$$, Typeset`animvar$$ = 1, Typeset`name$$ = 
     "\"untitled\"", Typeset`specs$$ = {{
       Hold[
        ActionMenu["display mode", {"Wireframe" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Wireframe", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Wireframe", "\" _Enter"], 
             False]), "Shaded" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Shaded", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Shaded", "\" _Enter"], 
             False]), "Rendered" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Rendered", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Rendered", "\" _Enter"], 
             False]), "Ghosted" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Ghosted", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Ghosted", "\" _Enter"], 
             False]), "X-Ray" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "X-Ray", "\" _Enter"], False]; 
           RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "X-Ray", "\" _Enter"], False])
           , "Technical" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Technical", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Technical", "\" _Enter"], 
             False]), "Artistic" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Artistic", "\" _Enter"], 
             False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Artistic", "\" _Enter"], 
             False]), "Pen" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Pen", "\" _Enter"], False]; 
           RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Pen", "\" _Enter"], False]), 
          "Raytraced with Neon" :> (RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Raytraced with Neon", 
              "\" _Enter"], False]; RhinoApp`RunScript[
             StringJoin[
             "_SetDisplayMode Viewport=All \"", "Raytraced with Neon", 
              "\" _Enter"], False])}, ImageSize -> Medium]], 
       Manipulate`Dump`ThisIsNotAControl}, {{
        Hold[$CellContext`l$$], 1, ""}, 1, 10, 1}, {{
        Hold[$CellContext`w$$], 1, ""}, 1, 10, 1}, {{
        Hold[$CellContext`h$$], 1, ""}, 1, 10, 1}, {{
        Hold[$CellContext`x$$], 0, ""}, 0, 10, 1}, {{
        Hold[$CellContext`y$$], 0, ""}, 0, 10, 1}, {{
        Hold[$CellContext`z$$], 0, ""}, 0, 10, 1}, {
       Hold[
        Grid[{{"length", 
           Manipulate`Place[1], "", "x", 
           Manipulate`Place[4]}, {"width", 
           Manipulate`Place[2], "", "y", 
           Manipulate`Place[5]}, {"height", 
           Manipulate`Place[3], "", "z", 
           Manipulate`Place[6]}}, Alignment -> {Right, Left, Right, Left}]], 
       Manipulate`Dump`ThisIsNotAControl}, {
       Hold[""], Manipulate`Dump`ThisIsNotAControl}, {
       Hold[
        Button["new box", $CellContext`guid$$ = $CellContext`doc$$[
            $CellContext`Objects[
             $CellContext`Add[
              Brep`CreateFromBox[
               NETLink`NETNew["Rhino.Geometry.BoundingBox", 
                NETLink`NETNew[
                "Rhino.Geometry.Point3d", $CellContext`x$$, $CellContext`y$$, \
$CellContext`z$$], 
                NETLink`NETNew[
                "Rhino.Geometry.Point3d", $CellContext`x$$ + \
$CellContext`l$$, $CellContext`y$$ + $CellContext`w$$, $CellContext`z$$ + \
$CellContext`h$$]]]]]]; $CellContext`doc$$[
           $CellContext`Views[
            $CellContext`Redraw[]]]]], Manipulate`Dump`ThisIsNotAControl}, {
       Hold[""], Manipulate`Dump`ThisIsNotAControl}}, Typeset`size$$ = {
     0., {0., 8.}}, Typeset`update$$ = 0, Typeset`initDone$$, 
     Typeset`skipInitDone$$ = False, $CellContext`l$928$$ = 
     0, $CellContext`w$933$$ = 0, $CellContext`h$934$$ = 
     0, $CellContext`x$935$$ = 0, $CellContext`y$936$$ = 
     0, $CellContext`z$937$$ = 0}, 
     DynamicBox[Manipulate`ManipulateBoxes[
      2, StandardForm, 
       "Variables" :> {$CellContext`h$$ = 1, $CellContext`l$$ = 
         1, $CellContext`w$$ = 1, $CellContext`x$$ = 0, $CellContext`y$$ = 
         0, $CellContext`z$$ = 0}, "ControllerVariables" :> {
         Hold[$CellContext`l$$, $CellContext`l$928$$, 0], 
         Hold[$CellContext`w$$, $CellContext`w$933$$, 0], 
         Hold[$CellContext`h$$, $CellContext`h$934$$, 0], 
         Hold[$CellContext`x$$, $CellContext`x$935$$, 0], 
         Hold[$CellContext`y$$, $CellContext`y$936$$, 0], 
         Hold[$CellContext`z$$, $CellContext`z$937$$, 0]}, 
       "OtherVariables" :> {
        Typeset`show$$, Typeset`bookmarkList$$, Typeset`bookmarkMode$$, 
         Typeset`animator$$, Typeset`animvar$$, Typeset`name$$, 
         Typeset`specs$$, Typeset`size$$, Typeset`update$$, 
         Typeset`initDone$$, Typeset`skipInitDone$$}, "Body" :> 
       NETLink`NETBlock[$CellContext`doc$$[
           $CellContext`Objects[
            Replace[$CellContext`guid$$, 
             Brep`CreateFromBox[
              NETLink`NETNew["Rhino.Geometry.BoundingBox", 
               NETLink`NETNew[
               "Rhino.Geometry.Point3d", $CellContext`x$$, $CellContext`y$$, \
$CellContext`z$$], 
               NETLink`NETNew[
               "Rhino.Geometry.Point3d", $CellContext`x$$ + $CellContext`l$$, \
$CellContext`y$$ + $CellContext`w$$, $CellContext`z$$ + \
$CellContext`h$$]]]]]]; $CellContext`doc$$[
           $CellContext`Views[
            $CellContext`Redraw[]]]; ""], "Specifications" :> {
         ActionMenu["display mode", {"Wireframe" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Wireframe", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Wireframe", "\" _Enter"], 
              False]), "Shaded" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Shaded", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Shaded", "\" _Enter"], 
              False]), "Rendered" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Rendered", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Rendered", "\" _Enter"], 
              False]), "Ghosted" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Ghosted", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Ghosted", "\" _Enter"], 
              False]), "X-Ray" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "X-Ray", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "X-Ray", "\" _Enter"], 
              False]), "Technical" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Technical", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Technical", "\" _Enter"], 
              False]), "Artistic" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Artistic", "\" _Enter"], 
              False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Artistic", "\" _Enter"], 
              False]), "Pen" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Pen", "\" _Enter"], False]; 
            RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Pen", "\" _Enter"], False]),
            "Raytraced with Neon" :> (RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Raytraced with Neon", 
               "\" _Enter"], False]; RhinoApp`RunScript[
              StringJoin[
              "_SetDisplayMode Viewport=All \"", "Raytraced with Neon", 
               "\" _Enter"], False])}, ImageSize -> Medium], 
         Delimiter, {{$CellContext`l$$, 1, ""}, 1, 10, 1, ImageSize -> Small, 
          ControlPlacement -> 1}, {{$CellContext`w$$, 1, ""}, 1, 10, 1, 
          ImageSize -> Small, ControlPlacement -> 
          2}, {{$CellContext`h$$, 1, ""}, 1, 10, 1, ImageSize -> Small, 
          ControlPlacement -> 3}, {{$CellContext`x$$, 0, ""}, 0, 10, 1, 
          ImageSize -> Small, ControlPlacement -> 
          4}, {{$CellContext`y$$, 0, ""}, 0, 10, 1, ImageSize -> Small, 
          ControlPlacement -> 5}, {{$CellContext`z$$, 0, ""}, 0, 10, 1, 
          ImageSize -> Small, ControlPlacement -> 6}, 
         Grid[{{"length", 
            Manipulate`Place[1], "", "x", 
            Manipulate`Place[4]}, {"width", 
            Manipulate`Place[2], "", "y", 
            Manipulate`Place[5]}, {"height", 
            Manipulate`Place[3], "", "z", 
            Manipulate`Place[6]}}, Alignment -> {Right, Left, Right, Left}], 
         "", 
         Button["new box", $CellContext`guid$$ = $CellContext`doc$$[
             $CellContext`Objects[
              $CellContext`Add[
               Brep`CreateFromBox[
                NETLink`NETNew["Rhino.Geometry.BoundingBox", 
                 NETLink`NETNew[
                 "Rhino.Geometry.Point3d", $CellContext`x$$, \
$CellContext`y$$, $CellContext`z$$], 
                 NETLink`NETNew[
                 "Rhino.Geometry.Point3d", $CellContext`x$$ + \
$CellContext`l$$, $CellContext`y$$ + $CellContext`w$$, $CellContext`z$$ + \
$CellContext`h$$]]]]]]; $CellContext`doc$$[
            $CellContext`Views[
             $CellContext`Redraw[]]]], ""}, "Options" :> {}, 
       "DefaultOptions" :> {}],
      ImageSizeCache->{42., {6., 11.}},
      SingleEvaluation->True],
     Deinitialization:>None,
     DynamicModuleValues:>{},
     Initialization:>(
      Block[{}, NETLink`LoadNETType["Rhino.RhinoDoc"]; 
        NETLink`LoadNETType["Rhino.Geometry.Brep"]; 
        NETLink`LoadNETType["Rhino.Display.DisplayModeDescription"]; 
        NETLink`LoadNETType["Rhino.RhinoApp"]; $CellContext`doc$$ = 
         RhinoDoc`ActiveDoc; $CellContext`guid$$ = $CellContext`doc$$[
           $CellContext`Objects[
            $CellContext`Add[
             Brep`CreateFromBox[
              NETLink`NETNew["Rhino.Geometry.BoundingBox", 
               NETLink`NETNew["Rhino.Geometry.Point3d", 0, 0, 0], 
               NETLink`NETNew[
               "Rhino.Geometry.Point3d", 1, 1, 1]]]]]]; $CellContext`doc$$[
          $CellContext`Views[
           $CellContext`Redraw[]]]]; Typeset`initDone$$ = True),
     SynchronousInitialization->True,
     UndoTrackedVariables:>{Typeset`show$$, Typeset`bookmarkMode$$},
     UnsavedVariables:>{Typeset`initDone$$},
     UntrackedVariables:>{Typeset`size$$}], "Manipulate",
    Deployed->True,
    StripOnInput->False],
   Manipulate`InterpretManipulate[1]],
  DynamicModuleValues:>{}]], "Output",
 CellChangeTimes->{
  3.668170447114008*^9},ExpressionUUID->"94d5a80b-5f3d-4df7-9758-\
555e311701f8"]
}, Open  ]]
}, Open  ]]
}, Open  ]]
},
Evaluator->"RhinoAttach",
WindowSize->{1049, 650},
WindowMargins->{{Automatic, 67}, {10, Automatic}},
Magnification:>1.4 Inherited,
FrontEndVersion->"11.3 for Microsoft Windows (64-bit) (March 6, 2018)",
StyleDefinitions->"Default.nb"
]
(* End of Notebook Content *)

(* Internal cache information *)
(*CellTagsOutline
CellTagsIndex->{}
*)
(*CellTagsIndex
CellTagsIndex->{}
*)
(*NotebookFileOutline
Notebook[{
Cell[CellGroupData[{
Cell[580, 22, 374, 6, 135, "Title",ExpressionUUID->"f934e75a-8f02-49ca-83d8-c79ba5b801fd"],
Cell[957, 30, 185, 2, 48, "Text",ExpressionUUID->"09d236c1-1394-4427-a88e-743caae89d70"],
Cell[1145, 34, 197, 3, 48, "Text",ExpressionUUID->"6c0e0dc9-3c31-439a-b773-4b0e70fd3ab6"],
Cell[1345, 39, 370, 8, 80, "Text",ExpressionUUID->"c3da9f8b-ac13-45ac-87b8-0ecf039bc4d3"],
Cell[1718, 49, 314, 7, 48, "Text",ExpressionUUID->"824a49db-09a4-4f39-9cf0-f65c144c7032"],
Cell[CellGroupData[{
Cell[2057, 60, 153, 3, 92, "Section",ExpressionUUID->"571f6223-53b4-452f-90af-6fb0e6651423"],
Cell[2213, 65, 283, 4, 113, "Text",ExpressionUUID->"3bc6e92a-7475-4fe8-a316-527ca4179321"]
}, Closed]],
Cell[CellGroupData[{
Cell[2533, 74, 152, 3, 71, "Section",ExpressionUUID->"5a626873-a455-47c0-9d7d-563dcb4caf65"],
Cell[2688, 79, 230, 4, 48, "Text",ExpressionUUID->"05e8fc1f-af24-411a-a303-6825d0808988"]
}, Open  ]],
Cell[CellGroupData[{
Cell[2955, 88, 242, 5, 92, "Section",ExpressionUUID->"af1b65cd-c32e-4617-95fe-7357994531af",
 InitializationGroup->True],
Cell[3200, 95, 171, 3, 113, "Text",ExpressionUUID->"394c5d7b-7b70-4a24-a708-c11c106486c8"],
Cell[3374, 100, 11712, 249, 4413, "Input",ExpressionUUID->"b68cf3d2-6ef4-4f9c-972d-12d8977d1b61"]
}, Closed]],
Cell[CellGroupData[{
Cell[15123, 354, 161, 3, 71, "Section",ExpressionUUID->"b0ccd80e-5534-4d72-9a41-1412106bc697"],
Cell[CellGroupData[{
Cell[15309, 361, 185, 3, 40, "Input",ExpressionUUID->"02b37985-8aff-4e0b-aa38-4919feb0b032"],
Cell[15497, 366, 12662, 254, 48, "Output",ExpressionUUID->"94d5a80b-5f3d-4df7-9758-555e311701f8"]
}, Open  ]]
}, Open  ]]
}, Open  ]]
}
]
*)

